import os
import json
from google import genai
from dotenv import load_dotenv

# Load the hidden environment variables
load_dotenv()

class ImageSentry:
    def __init__(self):
        # Pull key safely from the .env file
        self.gemini_api_key = os.getenv("GEMINI_API_KEY")
        self.client = genai.Client(api_key=self.gemini_api_key)

    def analyze_image(self, image_path):
        filename = os.path.basename(image_path)
        print(f"Sending {filename} to Gemini for AI generation analysis...")
        
        try:
            sample_file = self.client.files.upload(file=image_path, config={'display_name': 'Suspected AI Image'})
            
            prompt = """
            You are an expert digital forensics analyst specializing in AI image detection.
            Examine this uploaded image carefully for signs that it was generated by AI (e.g., Midjourney, Stable Diffusion, DALL-E).
            
            Look closely for common AI artifacts:
            1. Anatomical anomalies (e.g., weird hands, extra fingers, asymmetrical eyes, merged teeth).
            2. Unnatural textures, over-smoothing, or plastic-like skin.
            3. Nonsensical background text, gibberish signs, or mangled background objects.
            4. Lighting inconsistencies, physically impossible reflections, or floating items.
            
            Provide a JSON response with exactly these keys:
            - "ai_confidence": Score from 0 to 100 (100 = definitely AI, 0 = definitely real photography/art).
            - "is_ai": boolean (true if ai_confidence > 50, false otherwise).
            - "artifacts_detected": A list of strings detailing specific suspicious AI elements OR natural biological elements found.
            - "verdict_summary": A 1-2 sentence explanation of your final conclusion.

            Output ONLY valid JSON. Do not include markdown formatting.
            """

            response = self.client.models.generate_content(
                model='gemini-2.5-flash',
                contents=[sample_file, prompt]
            )
            
            self.client.files.delete(name=sample_file.name)

            raw_text = response.text.strip()
            if raw_text.startswith("```json"):
                raw_text = raw_text[7:-3].strip()
                
            ai_analysis = json.loads(raw_text)

        except Exception as e:
            return {"image_file": filename, "error": f"AI Analysis Blocked or Failed. System error: {str(e)}"}

        return {
            "image_file": filename,
            "is_ai": ai_analysis.get("is_ai", False),
            "ai_confidence": ai_analysis.get("ai_confidence", 0),
            "artifacts_detected": ai_analysis.get("artifacts_detected", ["No specific artifacts noted."]),
            "verdict_summary": ai_analysis.get("verdict_summary", "Analysis complete.")
        }